Incerase ios restrictions
jeetiss/image-fns pull request #9
Opened 2019-03-19 09:17 UTC by jeetiss

2019-03-20 05:23 UTC, bautrukevich approved these changes

2019-03-25 10:56 UTC, Zmoki commented
@jeetiss could you add a link to proof?

2019-04-02 11:59 UTC, jeetiss commented
I'm testing this using browserstack and [codepen demo](https://codepen.io/jeetiss/full/vPKrby)
Devices from iPhone 5se with iOS 9 have enough memory for work with 16 megapixels images

2019-04-03 10:03 UTC, Zmoki requested changes
add note to changelog

2019-04-05 10:41 UTC, Zmoki approved these changes

2019-04-09 07:52 UTC, merged